### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by patrickleet** [patrickleet/apply-template#6]
For some reason, contents of .gitignore file is not being copied over

**Comment by iketiunn** [comment]
line13
https://github.com/patrickleet/apply-template/blob/b033fbbc29d6c268f624a2a8be359e29db29f557/lib/gitignored.js#L13

line25
https://github.com/patrickleet/apply-template/blob/b033fbbc29d6c268f624a2a8be359e29db29f557/lib/gitignored.js#L25

line34-36
https://github.com/patrickleet/apply-template/blob/b033fbbc29d6c268f624a2a8be359e29db29f557/lib/gitignored.js#L34-L36

I found that because it always add`.git/` at the end of the ignore array, so when it transforms to regexes, it will be `...|\.git\/?|\.git\/(.+))`.

`?` will make both `.git/` and `.git` matched.

Which causes content in  `.gitignore` or any file name contains with `.git` to be empty.

**Comment by patrickleet** [comment]
good find, wanna make a PR?

tbh I haven't used this project in quite a while - this was made before Github had support for template repositories. To be fair those do not support variables.

**Comment by iketiunn** [comment]
Sorry, we use a bash approach to apply our templates now.

So I don't have much attention to this right now.

We get lots of inspiration from your project, thanks for your contribution!
